spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/web_admin_app
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
